name: Helm Deploy
description: Deploys a helm chart to Kubernetes
author: lykon
branding:
  icon: anchor
  color: gray-dark
inputs:
  release:
    description: Helm release name. Will be combined with track if set.
    required: true
  namespace:
    description: Kubernetes namespace name.
    required: true
  chart:
    description: Helm chart path. If set to "app" this will use the built in helm
      chart found in this repository.
    required: true
  values:
    description: Helm chart values, expected to be a YAML or JSON string.
    required: false
  dry-run:
    description: Task name. If the task is "remove" it will remove the configured
      helm release.
    required: false
  token:
    description: Github repository token. If included and the event is a deployment
      the deployment_status event will be fired.
    required: false
  value-files:
    description: Additional value files to apply to the helm chart. Expects JSON encoded
      array or a string.
    required: false
  secrets:
    description: Secret variables to include in value file interpolation. Expects
      JSON encoded map.
    required: false
  version:
    description: Version of the app, usually commit sha works here.
    required: false
  repo:
    description: Helm chart repository to be added.
    required: false
  repo-alias:
    description: Helm repository alias that will be used.
    required: false
  repo-username:
    description: Helm repository username if authentication is needed.
    required: false
  repo-password:
    description: Helm repository password if authentication is needed.
    required: false
runs:
  using: docker
  image: Dockerfile
